name: Generate pacman animation

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Faz o checkout do seu repositório para que a action possa acessá-lo
      - uses: actions/checkout@v3

      # Passo 2: Gera o gráfico como antes
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Nome do arquivo de saída
          svg_file_name: pacman-contribution-graph.svg
          # Diretório de saída
          output_dir: dist

      # Passo 3: Faz o commit do novo gráfico diretamente na branch 'main'
      - name: push pacman-contribution-graph.svg to the main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pacman contribution graph"
          file_pattern: dist/*.svg # Garante que apenas o arquivo SVG seja commitado
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
